DESIGN_NAME: dual_port
VERILOG_FILES: dir::rtl/*.sv
CLOCK_PERIOD: 40
CLOCK_PORT: clk_i
# Power Distribution Stuff
FP_PDN_VOFFSET: 7
FP_PDN_HOFFSET: 7
FP_PDN_SKIPTRIM: true
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GRT_DESIGN_REPAIR: true
FP_SIZING: absolute
DIE_AREA:
  - 0
  - 0
  - 2500
  - 2500
VDD_NETS:
- VPWR
GND_NETS:
- VGND
MACROS:
  DFFRAM256x32:
    instances:
      ram1:
        location:
        - 100
        - 1350
        orientation: S
      ram2:
        location:
        - 100
        - 750
        orientation: FS
    gds:
    - dir::macros/dffram256x32/layout/gds/DFFRAM256x32.gds.gz
    lef:
    - dir::macros/dffram256x32/layout/lef/DFFRAM256x32.lef
    spef:
      max*:
      - dir::macros/dffram256x32/timing/spef/DFFRAM256x32.max.spef
      min*:
      - dir::macros/dffram256x32/timing/spef/DFFRAM256x32.min.spef
      nom*:
      - dir::macros/dffram256x32/timing/spef/DFFRAM256x32.nom.spef
    lib:
      "*": dir::macros/dffram256x32/timing/lib/nom/DFFRAM256x32.Typical.lib
    nl:
    - dir::macros/dffram256x32/hdl/gl/DFFRAM256x32.v
    pnl:
    - dir::macros/dffram256x32/hdl/gl/DFFRAM256x32.v
PL_RESIZER_ALLOW_SETUP_VIOS: true
GRT_RESIZER_ALLOW_SETUP_VIOS: true
GRT_ANTENNA_ITERS: 15
GRT_ANTENNA_MARGIN: 15
RUN_HEURISTIC_DIODE_INSERTION: true
DESIGN_REPAIR_MAX_WIRE_LENGTH: 800
PL_WIRE_LENGTH_COEF: 0.05
RUN_POST_GRT_DESIGN_REPAIR: true
DESIGN_REPAIR_MAX_SLEW_PCT: 30
DESIGN_REPAIR_MAX_CAP_PCT: 30
MAX_TRANSITION_CONSTRAINT: 1.5
